### ISSUE TITLE
Correction backlog, mw_todo items

### ISSUE THREAD

**Issue by funderburkjim** [sanskrit-lexicon/csl-orig#1643] opened 2024-06-11 21:00 UTC
This issue for reconsidering items mentioned in [mw_todo.txt](https://github.com/user-attachments/files/15686568/mw_todo.txt) posted at #1639.

**Comment by funderburkjim** [comment] 2024-06-11 21:09
## incomplete Dhātup. references
Usually, the Dhātup. references (to Westergaard) in mw.txt have the form `<ls>Dhātup. xi, 15</ls>`.
But a few are missing the subsection number (e.g. 15).

[mw_todo_dhatup.txt](https://github.com/user-attachments/files/15794772/mw_todo_dhatup.txt) has proposed changes, all of which will be added to print changes.
@Andhrabharati There was one I could not find (root JF (back to slp1!)) in section xxvi. Can you find the subsection of Section 26 (xxvi)?

**Comment by Andhrabharati** [comment] 2024-06-11 23:16
It is at xxvi, 22 [jFz : जॄष्], @funderburkjim !

**Comment by funderburkjim** [comment] 2024-06-12 19:49
## बृहट्टिक ->बृहट्टिक्क
This is a good detective story -- Ending with a print change in MW as @aumsanskrit originally suggested.  I'll install this change (print change) to MW unless there are objections.

https://gist.github.com/funderburkjim/ba0316389ccc22f4718ee58ee9048e0e

**Comment by Andhrabharati** [comment] 2024-06-13 03:48
Just thought of "vetting" Jim's opening statement of [mw_todo_dhatup.txt](https://github.com/user-attachments/files/15794772/mw_todo_dhatup.txt)
> For some reason, MW did not put the subsection numbers in this reference

> There are only a few similar:
> 5 matches for "`<ls>Dhātup. [xivl]+</ls>`" in buffer: mw.txt

and a quick look into mw.txt data gave these results--
```
<ls n="Dhātup.">xxviii.</ls>	1
<ls>Dhāt.</ls>	2  ;; not even having section number
<ls>Dhātup.</ls>	213  ;; not even having section number
<ls>Dhātup. i.</ls>	1
<ls>Dhātup. iii.</ls>	1
<ls>Dhātup. xi.</ls>	1
<ls>Dhātup. xiii.</ls>	1
<ls>Dhātup. xiv.</ls>	1
<ls>Dhātup. xv.</ls>	1
<ls>Dhātup. xvi.</ls>	2
<ls>Dhātup. xix.</ls>	1
<ls>Dhātup. xx.</ls>	1
<ls>Dhātup. xxxii.</ls>	1
```

Jim might like to take some action against these.

**Comment by funderburkjim** [comment] 2024-06-13 18:53
[mw_todo_misc1.txt](https://github.com/user-attachments/files/15827373/mw_todo_misc1.txt) several submitted by Scott which Jim thinks have solution.

[mw_todo_insoluble_by_jim.txt](https://github.com/user-attachments/files/15827385/mw_todo_insoluble_by_jim.txt)  submitted by Scott. Jim has found no 'solution'.

**Comment by funderburkjim** [comment] 2024-06-13 20:04
[mw_todo_dhatup1.txt](https://github.com/user-attachments/files/15828009/mw_todo_dhatup1.txt)  subsection numbers for the additional cases AB mentions [above](https://github.com/sanskrit-lexicon/csl-orig/issues/1643#issuecomment-2164308596).

L=86537, tfR  `Dhātup. i.` not found.  There is a [reference to tfR](https://www.sanskrit-lexicon.uni-koeln.de/scans/csl-westergaard/disp/index.php?section=30)  at `Dhātup. xxx, 6` -
Should we change to `Dhātup. xxx, 6` -?

(

**Comment by funderburkjim** [comment] 2024-06-13 20:30
```
32327 matches in 32301 lines for "</lex> <ab>N.</ab>"
287 matches for "</lex>, <ab>N.</ab>" in buffer: mw.txt

Small random sample found no ',' after lex tag.
Conclude:
Global change.
"</lex>, <ab>N.</ab>" -> "</lex> <ab>N.</ab>"  287 changes.
```

**Comment by Andhrabharati** [comment] 2024-06-14 00:49
> L=86537, tfR `Dhātup. i.` not found. There is a [reference to tfR](https://www.sanskrit-lexicon.uni-koeln.de/scans/csl-westergaard/disp/index.php?section=30) at `Dhātup. xxx, 6` -
> Should we change to `Dhātup. xxx, 6` -?

It is , in fact, '1.' and not 'i.' here; as such the `<ls>Dhātup. i.</ls>` to be changed to `<ls>Dhātup.</ls>`

and then '1.' to be attached to the next word 'tṛta', i.e.,

```
<L>86538<pc>453,1<k1>tṛta<k2>tṛta<h>a<e>3 -> 
<s>tṛta</s> <hom>a</hom> ¦ 
```

to be changed as

```
<L>86538<pc>453,1<k1>tṛta<k2>tṛta<h>1<e>3
<hom>1.</hom> <s>tṛta</s> ¦
```

There were couple of places where this "1.  <> i." problem was corrected (in my working) and I had somehow missed this one; but got identified now (**for good**)!

**Comment by funderburkjim** [comment] 2024-06-14 01:09
```
37 matches for "</ab> -" in buffer: mw.txt  
  most of these to be changed to "</ab>-"  
```
The commit a65c65d shows the changes.

**Comment by funderburkjim** [comment] 2024-06-14 01:33
> tfta  86686

How about this?
```
OLD:
<L>86686<pc>453,3<k1>tfta<k2>tfta<h>b<e>1
<hom>1.</hom> and <hom>2.</hom> <s>tfta</s> <hom>b</hom>. ¦ See √ <s>tfR</s> and <s>trita/</s>.
<LEND>

NEW:
<L>86686<pc>453,3<k1>tfta<k2>tfta<h>a<e>1
<s>tfta</s> <hom>a<hom> ¦ [For <hom>1.</hom> of <s>tfta</s>, see √ <s>tfR</s>.]
<LEND>
<L>86686.1<pc>453,3<k1>tfta<k2>tfta<h>2<e>1
<hom>2.</hom> <s>tfta</s>¦ See <s>trita/</s>.
<LEND>
```

and 86538 as you have written
```
<L>86538<pc>453,1<k1>tfta<k2>tfta<h>1<e>3
<hom>1.</hom> <s>tfta</s> ¦ <lex>mfn.</lex> eaten <ab>g.</ab> <s>tanoty-Adi</s>.<info lex="m:f:n"/>
<LEND>
```

**Comment by Andhrabharati** [comment] 2024-06-14 01:44
Now, we have `<ls n="Dhātup.">iv f.</ls>` at 3 places (in CDSL) and at one grouped entry (in AB).

Should this get a roman number inside?

**Comment by Andhrabharati** [comment] 2024-06-14 01:48
> > tfta  86686
> 
> How about this?

Your suggestion is a bit too-much of a change, but still just retaining the original "sense" as is.
Probably we could leave the text "as is" at L- 86686 (at least for now!).

**Comment by funderburkjim** [comment] 2024-06-14 02:17
>  Re 86686

OK will leave untouched for now -- but I think my suggested recoding is much clearer!

Re traN[kKg]:  I think we should remove the 'f.' and put the 'correct' reference, different for each 1. These will be print changes.
```
<L>87413<pc>457,1<k1>traNk<k2>traNk<e>1
 294902:<s>traNk</s> ¦ <s>°NK</s>, <s>°Ng</s> <ab>cl.</ab> 1. <ab>id.</ab>, <ls n="Dhātup.">iv f.</ls><info verb="root" cp="1"/>
OLD: <ls n="Dhātup.">iv f.</ls>
NEW: <ls n="Dhātup.">iv, 23</ls>  त्रकि

---------------------------
<L>87413.1<pc>457,1<k1>traNK<k2>traNK<e>1
 294905:<s>traNK</s> ¦ <s>°Nk</s>, <s>°Ng</s> <ab>cl.</ab> 1. <ab>id.</ab>, <ls n="Dhātup.">iv f.</ls><info verb="root" cp="1"/>
OLD: <ls n="Dhātup.">iv f.</ls>
NEW: <ls n="Dhātup."v, 30</ls>  त्रखि

---------------------------
<L>87413.2<pc>457,1<k1>traNg<k2>traNg<e>1
 294908:<s>traNg</s> ¦ <s>°Nk</s>, <s>°NK</s> <ab>cl.</ab> 1. <ab>id.</ab>, <ls n="Dhātup.">iv f.</ls><info verb="root" cp="1"/>
OLD: <ls n="Dhātup.">iv f.</ls>
NEW: <ls n="Dhātup.">v, 42</ls>  त्रगि
```
Agree?

**Comment by Andhrabharati** [comment] 2024-06-14 02:33
Pl. go through this, @funderburkjim --
[mw_todo_insoluble (AB response).txt](https://github.com/user-attachments/files/15830891/mw_todo_insoluble.AB.response.txt)

**Comment by Andhrabharati** [comment] 2024-06-14 02:39
> > 
> 
> OK will leave untouched for now -- but I think my suggested recoding is much clearer!

I do agree that your recoding is clearer, but there are many places where such "correlative" referencing is present in MW & this would be just another one in the lot, i.e.,

`<hom>1.</hom> and <hom>2.</hom> <s>tfta</s>. ¦ See √ <s>tfR</s> and <s>trita/</s>.`
indicating

`<hom>1.</hom> <s>tfta</s>. ¦ See √ <s>tfR</s.`
and
`<hom>2.</hom> <s>tfta</s>. ¦ See <s>trita/</s>.`

**Comment by Andhrabharati** [comment] 2024-06-14 02:41
> > Re 86686
> 
> OK will leave untouched for now -- but I think my suggested recoding is much clearer!
> 
> Re traN[kKg]: I think we should remove the 'f.' and put the 'correct' reference, different for each 1. These will be print changes.
> 
> ```
> <L>87413<pc>457,1<k1>traNk<k2>traNk<e>1
>  294902:<s>traNk</s> ¦ <s>°NK</s>, <s>°Ng</s> <ab>cl.</ab> 1. <ab>id.</ab>, <ls n="Dhātup.">iv f.</ls><info verb="root" cp="1"/>
> OLD: <ls n="Dhātup.">iv f.</ls>
> NEW: <ls n="Dhātup.">iv, 23</ls>  त्रकि
> 
> ---------------------------
> <L>87413.1<pc>457,1<k1>traNK<k2>traNK<e>1
>  294905:<s>traNK</s> ¦ <s>°Nk</s>, <s>°Ng</s> <ab>cl.</ab> 1. <ab>id.</ab>, <ls n="Dhātup.">iv f.</ls><info verb="root" cp="1"/>
> OLD: <ls n="Dhātup.">iv f.</ls>
> NEW: <ls n="Dhātup.">v, 30</ls>  त्रखि
> 
> ---------------------------
> <L>87413.2<pc>457,1<k1>traNg<k2>traNg<e>1
>  294908:<s>traNg</s> ¦ <s>°Nk</s>, <s>°NK</s> <ab>cl.</ab> 1. <ab>id.</ab>, <ls n="Dhātup.">iv f.</ls><info verb="root" cp="1"/>
> OLD: <ls n="Dhātup.">iv f.</ls>
> NEW: <ls n="Dhātup.">v, 42</ls>  त्रगि
> ```
> 
> Agree?

Let me take some time for this.

**Comment by Andhrabharati** [comment] 2024-06-14 04:45
> [mw_todo_misc1.txt](https://github.com/user-attachments/files/15827373/mw_todo_misc1.txt) several submitted by Scott which Jim thinks have solution.

Here is my response to some of the entries that I felt necessary to talk on--
[mw_todo_misc1 (AB response).txt](https://github.com/user-attachments/files/15831686/mw_todo_misc1.AB.response.txt)

**Comment by Andhrabharati** [comment] 2024-06-14 17:22
> > Re traN[kKg]: I think we should remove the 'f.' and put the 'correct' reference, different for each 1. These will be print changes.
> > Agree?
> 
> Let me take some time for this.

Yes, these three roots at these resp. places; but could we mark them in the single entry itself?
```
<L>87413<pc>457,1<k1>traNk<k2>traNk<e>1
<s>traNk</s>, <s>°NK</s>, <s>°Ng</s> ¦ <ab>cl.</ab> 1. <ab>id.</ab>, <ls n="Dhātup.">iv, 23</ls>; <ls n="Dhātup.">v, 30</ls>; <ls n="Dhātup.">v, 42</ls>.<info verb="root" cp="1"/>
```

I do not wish to disturb the text file structure too much from the print matter; however we can split these grouped entries into individual sub-entries in the xml file, as done in GRA [which course of action has already been talked about].

**Comment by funderburkjim** [comment] 2024-06-14 17:34
Several (maybe 150) non-controversial changes in latest commit.

**Comment by funderburkjim** [comment] 2024-06-14 18:51
About 40 sanskrit word spelling corrections.  Details in the commits above.

**Comment by funderburkjim** [comment] 2024-06-14 21:02
## minor edits, 1

* kriz  4
* `,)` 20+
* ` of,`  30+ out of 600+ changed
* `11 matches for " and.*¦.*? <ab>N.</ab> of <ab>wk.</ab>"` 
  * surely many more 'wk' -> 'wks' to change, but how to find?

**Comment by funderburkjim** [comment] 2024-06-14 21:44
@aumsanskrit mentioned preferences for 'm. n.' over 'mn.'  
Went ahead a made this change (`<lex>mn.</lex> -> <lex>m.</lex> <lex>n.</lex>`)  About 600 changes

Similarly with `<lex>mf.</lex> -> <lex>m.</lex> <lex>f.</lex>`  About 150 changes.

This brings mw.txt slightly more close to print.

**Comment by funderburkjim** [comment] 2024-06-14 21:45
## two mw variations 
These are observations only, no action on mw.txt.

`132 matches for "<ls>KāśīKh.</ls>" in buffer: mw.txt` . 
 In print, some of these are spelled `Kāśīkh` (e.g. under hw = satpaTIna)
 Some are spelled `KāśīKh` (e.g. under hw = QuRQi).
 mw.txt uses only KāśīKh

`6 matches for "Piper Betle" in buffer: mw.txt` (e.g. hw = dAhadA)
`9 matches for "Piper Betel" in buffer: mw.txt` (e.g. hw = kuhali)
 The current *scientific name* is "Piper Betle", I think.
For some purposes, it might be good to change "Betel" to "Betle".

**Comment by funderburkjim** [comment] 2024-06-15 02:13
> mw_todo_misc1.AB.response.txt

- Changed the two as per the latest commits above
- Noticed mw72 also confirms Vajra-hūṇa

> - PWG's source Aufrecht has the alt. form "saukaraka"
> - Aufrecht to be in error (an extremely rare case), talking about one manuscript's content in the Oxford Library collection, that is the basis for PWG

@Andhrabharati  What is Aufrecht source that you mention?

**Comment by Andhrabharati** [comment] 2024-06-15 02:38
Verz. d. Oxf. H.

**Comment by Andhrabharati** [comment] 2024-06-15 03:08
BTW, your latest correction at L-81507 metaline

![image](https://github.com/sanskrit-lexicon/csl-orig/assets/75209130/6d6a6823-552d-4749-8dbc-f512b7d4c9f5)

is unwarranted, only adding another entity to the k1-k2 differring list!!

**Comment by aumsanskrit** [comment] 2024-06-15 03:55
Regarding the Headword "khārdamāyana", please recall that MW dictionary makes the following reference, "cf. kārd°. [ID=61878]".
![ khārdamāyana](https://github.com/sanskrit-lexicon/csl-orig/assets/105386121/cfa8bd1b-487a-45cf-bb85-43da2a1ecd87)

Andhrabharati has confirmed that the word, "kārdamāyana" exists as a variation, but my understanding is that a variation is NOT the same as "cf. kārd°".  Therefore, I am proposing a  "print change"  as follows:

"cf. kārd°"  should be changed to  "v.l. kārd°",  because MW dictionary does not include the Headword "kārdamāyana".

**Comment by Andhrabharati** [comment] 2024-06-15 04:16
Very good point raised, @Scott!

There are more such places that have cf. items that are not present in the same dictionary.

Probably we should make it a point to identify (sometime) and "correct" them as appropriate!

Jim, if you are willing, I have a strategy to deal with all such stuff, incl. `cf. <s>...</s>`; `See (or see) <s>...</s>` and `= <s>...</s>`

**Comment by Andhrabharati** [comment] 2024-06-15 05:56
> because MW dictionary does not include

Scott, I would like to bring to your notice my response against Case 142 in https://github.com/sanskrit-lexicon/csl-orig/issues/1643#issuecomment-2167102546; wherein (with the proposed change) the `<i>testudo</i>` remains under cf., but would not be "traceable" within MW.

So the correction won't always be changing cf. to v.l., but could be correcting the typo (or print) error, or changing the markup [which renders the the text as per print, but may not be present elsewhere within the dictionary].

**Comment by aumsanskrit** [comment] 2024-06-15 09:49
Thank you, Andhrabharati. I understand your point. One question remains regarding  "cf. testudo". How do we mark this word "testudo" so that it is understood to be a classical Latin word and not a Sanskrit word. Of course, I was initially thinking this was a reference to a Sanskrit word "testudo" which of course does not exist. There should be a way to clarify such references when they are NOT to a Sanskrit word.

**Comment by Andhrabharati** [comment] 2024-06-15 09:56
One option is to mark it as a "zoo(logical)" entity, which would be shown in a different style than the rest of the surrounding text.

But, Jim needs to accept doing so!

**Comment by Andhrabharati** [comment] 2024-06-15 15:54
> Case 642: ṭoṭa

I went through various lexicons for this again.

PWG & pwk just mention that ṭoṭa & ṭoṭī belong to the **gaurādi** gaṇa, and no meaning has been given.

However VCP & SKD has the words with the meanings alpa & hīna, while still citing them to belonging to the **gaurādi** gaṇa. They also give ḍoḍa and ḍoḍī, as the names of some plants. [**Same is the case, in PWG & its followers.**]
[Note: ḍoḍa is not explicitly present as a HW, but is equated with **kṣupaḍoḍamuṣṭi**.] (This is especially for Scott.)

It is quite probable that they could've been variant names for ṭoṭa & ṭoṭī, **though no explicit proof for the same could be got (in the little time that I had spent now)**.

So we could probably mark the body portion as **v. l. for ḍoḍ°** and close the case.

Are you happy now, Scott?

**Comment by aumsanskrit** [comment] 2024-06-16 08:37
Thank you, Andhrabharati. Yes, I am happy now.

By the way, you have written as follows — "Note: ḍoḍa is not explicitly present as a HW, but is equated with kṣupaḍoḍamuṣṭi."

Please see the image below showing the Headword डोड in MW dictionary.

![Uploading  DoDa.jpg…]()

**Comment by aumsanskrit** [comment] 2024-06-16 08:54
Trying to upload डोड again (but of course you can just look it up in MW dictionary):

![ DoDa](https://github.com/sanskrit-lexicon/csl-orig/assets/105386121/a66fa2fd-b1d5-4809-b6eb-443da8c4db6e)

**Comment by Andhrabharati** [comment] 2024-06-16 08:58
What I meant was, it is not in MW as a plant type!

**Comment by aumsanskrit** [comment] 2024-06-16 09:34
I understand.

By the way, while we are waiting for Jim to make some comments, I have one question that I am certain you can answer: 

Is there any difference between the two following diacritical markings for notating the anusvāra?

1)  ṁ

2)  ṃ

Or are they absolutely identical and interchangeable in all situtations?

**Comment by Andhrabharati** [comment] 2024-06-16 10:22
Good question indeed!

The simple answer is "these two are NOT always interchangeable".

Though ISO ṁ & and IAST ṃ are certainly interchangeable (both denoting the devanagari anusvāra), there are many cases where devanagari ardhānusvāra is transliterated as ṁ in Roman letters (in earlier works), i.e. before the IAST came into vogue in 1895 (after the Geneva Congress in 1894).

So, it all depends on which text (print) we are referring to!

**Comment by aumsanskrit** [comment] 2024-06-16 12:31
Thank you, Andhrabharati. I had been wondering about this for a few years, but too busy to investigate the answer.

**Comment by funderburkjim** [comment] 2024-06-16 19:49
`QuRQi—rAjoa` -> `QuRQi—rAja`  my typo corrected.

`<s>testudo</s>` -> `<bio>testudo</bio>`  Hurray for turtles!

`<ab>v.l.</ab> for <s>dow°</s>` -> `<ab>v.l.</ab> for <s>qoq°</s>`  (under 81295, 81295.1 ) print chg.

**Comment by funderburkjim** [comment] 2024-06-16 20:07
My next task is to resolve the k1-k2 mismatches (ref: https://github.com/sanskrit-lexicon/csl-orig/issues/1638#issuecomment-2155866315).

I think this will finish these various backlog issues.
However, there have been many discussions.  @aumsanskrit and @Andhrabharati  - please mention here other open questions that have solutions which I have yet not implemented.

**Comment by Andhrabharati** [comment] 2024-06-18 04:04
No pending items in this issue, @funderburkjim !

However, I would just like to remind you of [this](https://github.com/sanskrit-lexicon/csl-orig/issues/1643#issuecomment-2169064693) task.

**Comment by aumsanskrit** [comment] 2024-06-18 07:25
I did mention as follows, regarding the Headword “Khārdamāyana  [ID=61878]”.

Andhrabharati has confirmed that the word, "kārdamāyana" exists as a variation, but my understanding is that a variation is NOT the same as "cf. kārd°". Therefore, I am proposing a "print change" as follows:

"cf. kārd°" should be changed to "v.l. kārd°", because MW dictionary does not include the Headword "kārdamāyana".

**Comment by funderburkjim** [comment] 2024-06-21 01:43
made the change re Khārdamāyana.

**Comment by Andhrabharati** [comment] 2024-06-22 14:08
@funderburkjim 

After finishing the linking of Verz. d. Oxf. H. at PWG (and pwk), you can close this issue.

**Closed** 2024-06-23 19:54 UTC
