### ISSUE TITLE
mw:192970

### ISSUE THREAD

**Issue by funderburkjim** [sanskrit-lexicon/csl-orig#449] opened 2021-01-11 21:46 UTC
date:	01/05/2021 20:12:56
dict:	mw
Lnum:	192970
hw:	वि॑—घटिका 
old:	1/23
new:	1/60
comm:	vighatika is 1/60 of ghatika

**Comment by funderburkjim** [comment] 2021-01-12 21:49
This is a factual question, as 1/23 agrees with the scan.

AP : A measure of time equal to one-sixtieth part of a Ghaṭikā (or nearly equal to 24 seconds). 

VCP :  GawikAzazWiBAge

WIL: Sixtieth part of a Gharī, equal to 24 seconds.   (a GharI  = GawikA)

PWG: ein best. Zeitmaass, =  ?1/23  Ghaṭikā

It looks to me like MW has copied PWG.

I will change to 1/60 and note as a print change in MW.

Request comment from others.

**Comment by gasyoun** [comment] 2021-01-12 22:27
> It looks to me like MW has copied PWG.

As usual. In 95% of cases.

> I will change to 1/60 and note as a print change in MW.

Yes.

> Request comment from others.

@SergeA ?

**Comment by SergeA** [comment] 2021-01-21 05:25
I see the different statemensts but do not see any proof here. So why should it be changed?

**Comment by SergeA** [comment] 2021-01-21 05:53
Actually i´m against such changes. The digital version of the dictionary must provide a reliable copy of the printed book. Here Monier clearly states vighaṭikā to be "1/23" of ghaṭikā. But now in the site we read it as "1/60". Then somebody wants to quote MW's opinion and he will be misled by this change and will get false quotation.

**Comment by funderburkjim** [comment] 2021-01-21 21:11
The current procedure is to note such changes in a 'printchange' file for the dictionary, for mw this is file

[mw_printchange.txt](https://github.com/sanskrit-lexicon/csl-corrections/blob/master/dictionaries/mw/mw_printchange.txt).

At the bottom of the printchange file is an entry pertaining to this correction:
```
-----------------------------------------------------------------------
01-12-2021
ref: https://github.com/sanskrit-lexicon/csl-orig/issues/449
User: Unknown
L code : Headword : Old  : New : Comment
192970 : viGawikA : 1/23 of a Ghaṭikā : 1/60 of a Ghaṭikā :
```

**Comment by funderburkjim** [comment] 2021-01-21 21:14
Currently, the information in these print change files is not represented in any way in the displays or in the base
form of the digitization  (e.g. [mw.txt](https://github.com/sanskrit-lexicon/csl-orig/blob/master/v02/mw/mw.txt))

Would your concern be addressed by some integration of the printchange file information into mw.txt and then into displays?

**Comment by gasyoun** [comment] 2021-01-21 21:17
> Would your concern be addressed by some integration of the printchange file information into mw.txt and then into displays?

Guess so. Changes have to be made, not noted as well.

**Comment by drdhaval2785** [comment] 2021-08-07 04:38
The issue is resolved. Closing it.

**Closed by drdhaval2785** 2021-08-07 04:38 UTC
Labels: help wanted, print change
